version: "3"

services:
  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - TZ=America/Whitehorse
    volumes:
      - mongo-data:/data/db
      - ./dump:/dump
    ports:
      - 27017:27017

  db:
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
    user: root
    environment:
      DB_HOST: "localhost"
      MSSQL_SA_PASSWORD: YourStrong!Passw0rd
      TZ: "America/Whitehorse"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data

  mail:
    image: maildev/maildev:2.2.1
    environment:
      MAILDEV_INCOMING_USER: dev
      MAILDEV_INCOMING_PASS: dev123
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP

volumes:
  mongo-data:
  db_data:
